worker_processes 1;

events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;

  server {
    listen 80;

    location /authelia {
      proxy_pass http://authelia:9091;
    }

    location /gitea/ {
      auth_request /authelia;
      proxy_pass http://gitea:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /grafana/ {
      auth_request /authelia;
      proxy_pass http://grafana:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /authelia {
      internal;
      proxy_pass http://authelia:9091/api/verify;
      proxy_set_header Content-Length "";
      proxy_pass_request_body off;
    }
  }
}

